name: Noob
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Find and Replace Base
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          find: "test"
          replace: "sed"
      - name: Find and Replace Notebook
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          find: "hi"
          replace: "bye"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Dask version to ${{ steps.latest_version.outputs.version }}"
          title: "Update Dask version to ${{ steps.latest_version.outputs.version }}"
          reviewers: "jacobtomlinson"
          branch: "upgrade-dask-version"
          body: |
            A new Dask version has been detected.

            Updated `Dockerfile`s to use `${{ steps.latest_version.outputs.version }}`.
