name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Find and Replace
      uses: shitiomatic/str-replace@master
      with:
        find: "hello"
        replace: "world"


    - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Test"
          title: "Kek"
          reviewers: "StarkxD"
          branch: "Test"
          body: |
            Sed
